
spring:
  application:
    name: netology-diploma
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: mysecretpassword
  jpa:
    properties:
      hibernate:
        default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: none

server:
  port: 8090

token:
  secret: chIkRP2sVNyDbdFcL1VLxdnjjxPV4lYt52peqzzJ0N5xvS1OZ7sfiI0NOMpL0OTYdkwjIJBZlmjElUrlmrX8pwdL2YLgSydIxWZk
  expirationMs: 600000

